CREATE DATABASE items;
CREATE ROLE items_user WITH LOGIN ENCRYPTED PASSWORD 'items_user';
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO items_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO items_user;
