spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            item-categories-service: 
                - service-id: ${item-categories-service.name}
                  instance-id: item-categories-service1
                  host: ${ITEM_CATEGORIES_SERVICE_NAME}
                  port: ${ITEM_CATEGORIES_SERVICE_PORT}