spring:
  application:
    name: Items K8S Service

  datasource:
    url: jdbc:postgresql://localhost/items
    username: items_user
    password: items_user
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true

    circuitbreakers:
      enabled: true

    ratelimiters:
      enabled: true
    
    readinessstate:
      enabled: true
  
resilience4j:
  circuitbreaker:
    backends:
      item-categories-cb:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 50s
        permitted-number-of-calls-in-half-open-state: 2
        slow-call-rate-threshold: 65
        slow-call-duration-threshold: 3s